build:
  version: "v0.0.2"

support:
  message: "Bienvenidos al sistema Clientes de Accenture - Sistema en Produccion"
  contactInfo:
    name: "Product Owner - Clientes"
    email: "product.owner@accenture.com"
  phoneNumbers:
    - "(57) 3233223330"
    - "(57) 3102323322"