build:
  version: "v0.0.2"

support:
  message: "Bienvenidos al sistema Clientes Accenture - Sistema de pruebas"
  contactInfo:
    name: "QA - Clientes"
    email: "product.tester@accenture.com"
  phoneNumbers:
    - "(57) 3233223330"
    - "(57) 3102323322"